"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
import os
from setuptools import setup

birdsNames = []
for file in os.listdir('images'):
    birdsNames.append('images/' + file)

APP = ['main.py']
DATA_FILES = ['birds.csv', ('images', birdsNames)]

OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)