"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app resp. python3 setup.py py2app
"""
import os
from setuptools import setup

bird_names = []
for file in os.listdir('images'):
    bird_names.append('images/' + file)

APP = ['main.py']
DATA_FILES = ['birds.csv', ('images', bird_names)]

OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)